// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_pjrt_RCPPEXPORTS_H_GEN_
#define RCPP_pjrt_RCPPEXPORTS_H_GEN_

#include "pjrt_types.h"
#include <Rcpp.h>

namespace pjrt {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("pjrt", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("pjrt", "_pjrt_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in pjrt");
            }
        }
    }

    inline SEXP execute(SEXP executable, Rcpp::List inputs, SEXP options) {
        typedef SEXP(*Ptr_execute)(SEXP,SEXP,SEXP);
        static Ptr_execute p_execute = NULL;
        if (p_execute == NULL) {
            validateSignature("SEXP(*execute)(SEXP,Rcpp::List,SEXP)");
            p_execute = (Ptr_execute)R_GetCCallable("pjrt", "_pjrt_execute");
        }
        RObject rcpp_result_gen;
        {
            rcpp_result_gen = p_execute(Shield<SEXP>(Rcpp::wrap(executable)), Shield<SEXP>(Rcpp::wrap(inputs)), Shield<SEXP>(Rcpp::wrap(options)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<SEXP >(rcpp_result_gen);
    }

    inline SEXP buffer_from_r(SEXP client, SEXP device, SEXP data, std::vector<int64_t> dims, std::string dtype) {
        typedef SEXP(*Ptr_buffer_from_r)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_buffer_from_r p_buffer_from_r = NULL;
        if (p_buffer_from_r == NULL) {
            validateSignature("SEXP(*buffer_from_r)(SEXP,SEXP,SEXP,std::vector<int64_t>,std::string)");
            p_buffer_from_r = (Ptr_buffer_from_r)R_GetCCallable("pjrt", "_pjrt_buffer_from_r");
        }
        RObject rcpp_result_gen;
        {
            rcpp_result_gen = p_buffer_from_r(Shield<SEXP>(Rcpp::wrap(client)), Shield<SEXP>(Rcpp::wrap(device)), Shield<SEXP>(Rcpp::wrap(data)), Shield<SEXP>(Rcpp::wrap(dims)), Shield<SEXP>(Rcpp::wrap(dtype)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<SEXP >(rcpp_result_gen);
    }

    inline SEXP buffer_empty(SEXP client, SEXP device, std::vector<int64_t> dims, std::string dtype) {
        typedef SEXP(*Ptr_buffer_empty)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_buffer_empty p_buffer_empty = NULL;
        if (p_buffer_empty == NULL) {
            validateSignature("SEXP(*buffer_empty)(SEXP,SEXP,std::vector<int64_t>,std::string)");
            p_buffer_empty = (Ptr_buffer_empty)R_GetCCallable("pjrt", "_pjrt_buffer_empty");
        }
        RObject rcpp_result_gen;
        {
            rcpp_result_gen = p_buffer_empty(Shield<SEXP>(Rcpp::wrap(client)), Shield<SEXP>(Rcpp::wrap(device)), Shield<SEXP>(Rcpp::wrap(dims)), Shield<SEXP>(Rcpp::wrap(dtype)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<SEXP >(rcpp_result_gen);
    }

    inline SEXP buffer_copy_to_device(SEXP buffer, SEXP device, SEXP dst_client, bool cross_client) {
        typedef SEXP(*Ptr_buffer_copy_to_device)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_buffer_copy_to_device p_buffer_copy_to_device = NULL;
        if (p_buffer_copy_to_device == NULL) {
            validateSignature("SEXP(*buffer_copy_to_device)(SEXP,SEXP,SEXP,bool)");
            p_buffer_copy_to_device = (Ptr_buffer_copy_to_device)R_GetCCallable("pjrt", "_pjrt_buffer_copy_to_device");
        }
        RObject rcpp_result_gen;
        {
            rcpp_result_gen = p_buffer_copy_to_device(Shield<SEXP>(Rcpp::wrap(buffer)), Shield<SEXP>(Rcpp::wrap(device)), Shield<SEXP>(Rcpp::wrap(dst_client)), Shield<SEXP>(Rcpp::wrap(cross_client)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<SEXP >(rcpp_result_gen);
    }

    inline SEXP execution_options(std::vector<int64_t> non_donatable_indices, int launch_id) {
        typedef SEXP(*Ptr_execution_options)(SEXP,SEXP);
        static Ptr_execution_options p_execution_options = NULL;
        if (p_execution_options == NULL) {
            validateSignature("SEXP(*execution_options)(std::vector<int64_t>,int)");
            p_execution_options = (Ptr_execution_options)R_GetCCallable("pjrt", "_pjrt_execution_options");
        }
        RObject rcpp_result_gen;
        {
            rcpp_result_gen = p_execution_options(Shield<SEXP>(Rcpp::wrap(non_donatable_indices)), Shield<SEXP>(Rcpp::wrap(launch_id)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<SEXP >(rcpp_result_gen);
    }

}

#endif // RCPP_pjrt_RCPPEXPORTS_H_GEN_
