# Emit the translation unit that carries pjrt's precompiled CUDA kernels.
#
# `configure` compiles each src/cuda/*.cu into a fatbin and calls this to turn
# them into byte arrays the linker can put in the shared object, so that no
# part of the install has to find a file on disk at run time. This is what
# bin2c does, done in R because R is the one tool a package build is
# guaranteed to have.
#
# Called with no fatbins -- the build found no usable nvcc -- it still writes a
# valid translation unit, with a count of zero. src/cuda_kernels.h explains
# what the rest of the package makes of that.
#
# Usage: Rscript tools/embed_fatbin.R <out.cpp> [<stem>.fatbin ...]
# Each fatbin is assumed to have come from the sibling <stem>.cu.

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 1L) {
  stop("usage: embed_fatbin.R <out.cpp> [<stem>.fatbin ...]", call. = FALSE)
}
out_path <- args[[1L]]
fatbins <- args[-1L]

# 16 bytes a line: wide enough that the file isn't absurdly long, narrow
# enough that compilers and diff tools stay comfortable.
as_c_array <- function(bytes) {
  hex <- sprintf("0x%02x", as.integer(bytes))
  rows <- split(hex, (seq_along(hex) - 1L) %/% 16L)
  paste0("    ", vapply(rows, paste, character(1), collapse = ", "), collapse = ",\n")
}

arrays <- character()
entries <- character()

for (i in seq_along(fatbins)) {
  path <- fatbins[[i]]
  bytes <- readBin(path, "raw", n = file.size(path))
  symbol <- sprintf("kFatbin%d", i - 1L)
  source <- paste0(tools::file_path_sans_ext(basename(path)), ".cu")

  arrays <- c(
    arrays,
    sprintf(
      "// %s (%d bytes)\nconst unsigned char %s[] = {\n%s};\n",
      source,
      length(bytes),
      symbol,
      as_c_array(bytes)
    )
  )
  entries <- c(entries, sprintf('    {"%s", %s, %du},', source, symbol, length(bytes)))
}

if (length(entries) == 0L) {
  # A zero-length array is not valid C++, so leave one unread placeholder
  # behind and let kCudaFatbinCount say there is nothing here.
  entries <- "    {nullptr, nullptr, 0u},  // placeholder: this build has no CUDA kernels"
}

writeLines(
  c(
    "// Generated by tools/embed_fatbin.R during configure -- do not edit.",
    "//",
    "// Holds the device code compiled from src/cuda/*.cu, one fatbin per",
    "// source file. See src/cuda_kernels.h for how it is loaded.",
    '#include "cuda_kernels.h"',
    "",
    "namespace rpjrt {",
    "namespace {",
    "",
    arrays,
    "}  // namespace",
    "",
    "const CudaFatbin kCudaFatbins[] = {",
    entries,
    "};",
    sprintf("const unsigned int kCudaFatbinCount = %du;", length(fatbins)),
    "",
    "}  // namespace rpjrt"
  ),
  out_path
)
