// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "pjrt_types.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// impl_dispatch_node_selftest
Rcpp::List impl_dispatch_node_selftest(SEXP x);
RcppExport SEXP _pjrt_impl_dispatch_node_selftest(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_dispatch_node_selftest(x));
    return rcpp_result_gen;
END_RCPP
}
// impl_dispatch_key_hash
std::string impl_dispatch_key_hash(Rcpp::List leaves);
RcppExport SEXP _pjrt_impl_dispatch_key_hash(SEXP leavesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type leaves(leavesSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_dispatch_key_hash(leaves));
    return rcpp_result_gen;
END_RCPP
}
// impl_dispatch_key_eq
bool impl_dispatch_key_eq(Rcpp::List a, Rcpp::List b);
RcppExport SEXP _pjrt_impl_dispatch_key_eq(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_dispatch_key_eq(a, b));
    return rcpp_result_gen;
END_RCPP
}
// impl_dispatch_static_key_eq
bool impl_dispatch_static_key_eq(Rcpp::List a, Rcpp::List b);
RcppExport SEXP _pjrt_impl_dispatch_static_key_eq(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_dispatch_static_key_eq(a, b));
    return rcpp_result_gen;
END_RCPP
}
// impl_dispatch_lru_selftest
Rcpp::IntegerVector impl_dispatch_lru_selftest();
RcppExport SEXP _pjrt_impl_dispatch_lru_selftest() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(impl_dispatch_lru_selftest());
    return rcpp_result_gen;
END_RCPP
}
// impl_dispatch_sentinel
SEXP impl_dispatch_sentinel();
RcppExport SEXP _pjrt_impl_dispatch_sentinel() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(impl_dispatch_sentinel());
    return rcpp_result_gen;
END_RCPP
}
// impl_dispatch_create
SEXP impl_dispatch_create(int capacity, SEXP miss_fn);
RcppExport SEXP _pjrt_impl_dispatch_create(SEXP capacitySEXP, SEXP miss_fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type capacity(capacitySEXP);
    Rcpp::traits::input_parameter< SEXP >::type miss_fn(miss_fnSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_dispatch_create(capacity, miss_fn));
    return rcpp_result_gen;
END_RCPP
}
// impl_dispatch_size
int impl_dispatch_size(SEXP handle);
RcppExport SEXP _pjrt_impl_dispatch_size(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_dispatch_size(handle));
    return rcpp_result_gen;
END_RCPP
}
// impl_dispatch_run
SEXP impl_dispatch_run(SEXP handle, Rcpp::List args);
RcppExport SEXP _pjrt_impl_dispatch_run(SEXP handleSEXP, SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_dispatch_run(handle, args));
    return rcpp_result_gen;
END_RCPP
}
// get_eigh_handler
SEXP get_eigh_handler();
RcppExport SEXP _pjrt_get_eigh_handler() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_eigh_handler());
    return rcpp_result_gen;
END_RCPP
}
// get_eigh_handler_cuda
SEXP get_eigh_handler_cuda();
RcppExport SEXP _pjrt_get_eigh_handler_cuda() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_eigh_handler_cuda());
    return rcpp_result_gen;
END_RCPP
}
// impl_register_custom_call
void impl_register_custom_call(Rcpp::XPtr<rpjrt::PJRTPlugin> plugin, const std::string& target_name, SEXP handler_ptr, const std::string& platform_name);
RcppExport SEXP _pjrt_impl_register_custom_call(SEXP pluginSEXP, SEXP target_nameSEXP, SEXP handler_ptrSEXP, SEXP platform_nameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTPlugin> >::type plugin(pluginSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type target_name(target_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type handler_ptr(handler_ptrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type platform_name(platform_nameSEXP);
    impl_register_custom_call(plugin, target_name, handler_ptr, platform_name);
    return R_NilValue;
END_RCPP
}
// get_print_handler
SEXP get_print_handler();
RcppExport SEXP _pjrt_get_print_handler() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_print_handler());
    return rcpp_result_gen;
END_RCPP
}
// get_print_handler_cuda
SEXP get_print_handler_cuda();
RcppExport SEXP _pjrt_get_print_handler_cuda() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_print_handler_cuda());
    return rcpp_result_gen;
END_RCPP
}
// test_get_extension
bool test_get_extension(Rcpp::XPtr<rpjrt::PJRTPlugin> plugin, const std::string& platform_name);
RcppExport SEXP _pjrt_test_get_extension(SEXP pluginSEXP, SEXP platform_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTPlugin> >::type plugin(pluginSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type platform_name(platform_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(test_get_extension(plugin, platform_name));
    return rcpp_result_gen;
END_RCPP
}
// format_raw_buffer_cpp
CharacterVector format_raw_buffer_cpp(RawVector data, std::string dtype, IntegerVector shape);
RcppExport SEXP _pjrt_format_raw_buffer_cpp(SEXP dataSEXP, SEXP dtypeSEXP, SEXP shapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type shape(shapeSEXP);
    rcpp_result_gen = Rcpp::wrap(format_raw_buffer_cpp(data, dtype, shape));
    return rcpp_result_gen;
END_RCPP
}
// impl_gc_call_count
std::size_t impl_gc_call_count();
RcppExport SEXP _pjrt_impl_gc_call_count() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(impl_gc_call_count());
    return rcpp_result_gen;
END_RCPP
}
// impl_call_r_gc
void impl_call_r_gc();
RcppExport SEXP _pjrt_impl_call_r_gc() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    impl_call_r_gc();
    return R_NilValue;
END_RCPP
}
// get_lu_handler
SEXP get_lu_handler();
RcppExport SEXP _pjrt_get_lu_handler() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_lu_handler());
    return rcpp_result_gen;
END_RCPP
}
// get_lu_handler_cuda
SEXP get_lu_handler_cuda();
RcppExport SEXP _pjrt_get_lu_handler_cuda() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_lu_handler_cuda());
    return rcpp_result_gen;
END_RCPP
}
// impl_plugin_load
Rcpp::XPtr<rpjrt::PJRTPlugin> impl_plugin_load(const std::string& path);
RcppExport SEXP _pjrt_impl_plugin_load(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_plugin_load(path));
    return rcpp_result_gen;
END_RCPP
}
// impl_plugin_client_create
Rcpp::XPtr<rpjrt::PJRTClient> impl_plugin_client_create(Rcpp::XPtr<rpjrt::PJRTPlugin> plugin, Rcpp::Nullable<Rcpp::List> options);
RcppExport SEXP _pjrt_impl_plugin_client_create(SEXP pluginSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTPlugin> >::type plugin(pluginSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_plugin_client_create(plugin, options));
    return rcpp_result_gen;
END_RCPP
}
// impl_program_load
Rcpp::XPtr<rpjrt::PJRTProgram> impl_program_load(const std::string& fname, const std::string& format);
RcppExport SEXP _pjrt_impl_program_load(SEXP fnameSEXP, SEXP formatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type format(formatSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_program_load(fname, format));
    return rcpp_result_gen;
END_RCPP
}
// impl_program_repr
std::string impl_program_repr(Rcpp::XPtr<rpjrt::PJRTProgram> program, int n);
RcppExport SEXP _pjrt_impl_program_repr(SEXP programSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTProgram> >::type program(programSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_program_repr(program, n));
    return rcpp_result_gen;
END_RCPP
}
// impl_build_options_create
Rcpp::XPtr<rpjrt::PJRTBuildOptions> impl_build_options_create(const int num_replicas, const int num_partitions, const int device_ordinal);
RcppExport SEXP _pjrt_impl_build_options_create(SEXP num_replicasSEXP, SEXP num_partitionsSEXP, SEXP device_ordinalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type num_replicas(num_replicasSEXP);
    Rcpp::traits::input_parameter< const int >::type num_partitions(num_partitionsSEXP);
    Rcpp::traits::input_parameter< const int >::type device_ordinal(device_ordinalSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_build_options_create(num_replicas, num_partitions, device_ordinal));
    return rcpp_result_gen;
END_RCPP
}
// impl_compile_options_create
Rcpp::XPtr<rpjrt::PJRTCompileOptions> impl_compile_options_create(Rcpp::XPtr<rpjrt::PJRTBuildOptions> build_options);
RcppExport SEXP _pjrt_impl_compile_options_create(SEXP build_optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTBuildOptions> >::type build_options(build_optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_compile_options_create(build_options));
    return rcpp_result_gen;
END_RCPP
}
// impl_client_program_compile
Rcpp::XPtr<rpjrt::PJRTLoadedExecutable> impl_client_program_compile(Rcpp::XPtr<rpjrt::PJRTClient> client, Rcpp::XPtr<rpjrt::PJRTDevice> device, Rcpp::XPtr<rpjrt::PJRTProgram> program, Rcpp::XPtr<rpjrt::PJRTCompileOptions> compile_options);
RcppExport SEXP _pjrt_impl_client_program_compile(SEXP clientSEXP, SEXP deviceSEXP, SEXP programSEXP, SEXP compile_optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTClient> >::type client(clientSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTDevice> >::type device(deviceSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTProgram> >::type program(programSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTCompileOptions> >::type compile_options(compile_optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_client_program_compile(client, device, program, compile_options));
    return rcpp_result_gen;
END_RCPP
}
// impl_loaded_executable_device
Rcpp::XPtr<rpjrt::PJRTDevice> impl_loaded_executable_device(Rcpp::XPtr<rpjrt::PJRTLoadedExecutable> executable);
RcppExport SEXP _pjrt_impl_loaded_executable_device(SEXP executableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTLoadedExecutable> >::type executable(executableSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_loaded_executable_device(executable));
    return rcpp_result_gen;
END_RCPP
}
// impl_client_buffer_from_raw
Rcpp::XPtr<rpjrt::PJRTBuffer> impl_client_buffer_from_raw(Rcpp::XPtr<rpjrt::PJRTClient> client, Rcpp::XPtr<rpjrt::PJRTDevice> device, SEXP data, std::vector<int64_t> dims, std::string dtype, bool row_major);
RcppExport SEXP _pjrt_impl_client_buffer_from_raw(SEXP clientSEXP, SEXP deviceSEXP, SEXP dataSEXP, SEXP dimsSEXP, SEXP dtypeSEXP, SEXP row_majorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTClient> >::type client(clientSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTDevice> >::type device(deviceSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::vector<int64_t> >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    Rcpp::traits::input_parameter< bool >::type row_major(row_majorSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_client_buffer_from_raw(client, device, data, dims, dtype, row_major));
    return rcpp_result_gen;
END_RCPP
}
// impl_client_buffer_empty
Rcpp::XPtr<rpjrt::PJRTBuffer> impl_client_buffer_empty(Rcpp::XPtr<rpjrt::PJRTClient> client, Rcpp::XPtr<rpjrt::PJRTDevice> device, std::vector<int64_t> dims, std::string dtype);
RcppExport SEXP _pjrt_impl_client_buffer_empty(SEXP clientSEXP, SEXP deviceSEXP, SEXP dimsSEXP, SEXP dtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTClient> >::type client(clientSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTDevice> >::type device(deviceSEXP);
    Rcpp::traits::input_parameter< std::vector<int64_t> >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_client_buffer_empty(client, device, dims, dtype));
    return rcpp_result_gen;
END_RCPP
}
// impl_buffer_to_raw
Rcpp::RawVector impl_buffer_to_raw(Rcpp::XPtr<rpjrt::PJRTClient> client, Rcpp::XPtr<rpjrt::PJRTBuffer> buffer, bool row_major);
RcppExport SEXP _pjrt_impl_buffer_to_raw(SEXP clientSEXP, SEXP bufferSEXP, SEXP row_majorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTClient> >::type client(clientSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTBuffer> >::type buffer(bufferSEXP);
    Rcpp::traits::input_parameter< bool >::type row_major(row_majorSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_buffer_to_raw(client, buffer, row_major));
    return rcpp_result_gen;
END_RCPP
}
// impl_buffer_copy_to_device
Rcpp::XPtr<rpjrt::PJRTBuffer> impl_buffer_copy_to_device(Rcpp::XPtr<rpjrt::PJRTBuffer> buffer, Rcpp::XPtr<rpjrt::PJRTDevice> device, Rcpp::XPtr<rpjrt::PJRTClient> dst_client, bool cross_client);
RcppExport SEXP _pjrt_impl_buffer_copy_to_device(SEXP bufferSEXP, SEXP deviceSEXP, SEXP dst_clientSEXP, SEXP cross_clientSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTBuffer> >::type buffer(bufferSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTDevice> >::type device(deviceSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTClient> >::type dst_client(dst_clientSEXP);
    Rcpp::traits::input_parameter< bool >::type cross_client(cross_clientSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_buffer_copy_to_device(buffer, device, dst_client, cross_client));
    return rcpp_result_gen;
END_RCPP
}
// impl_client_platform
std::string impl_client_platform(Rcpp::XPtr<rpjrt::PJRTClient> client);
RcppExport SEXP _pjrt_impl_client_platform(SEXP clientSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTClient> >::type client(clientSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_client_platform(client));
    return rcpp_result_gen;
END_RCPP
}
// impl_client_devices
Rcpp::List impl_client_devices(Rcpp::XPtr<rpjrt::PJRTClient> client);
RcppExport SEXP _pjrt_impl_client_devices(SEXP clientSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTClient> >::type client(clientSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_client_devices(client));
    return rcpp_result_gen;
END_RCPP
}
// impl_buffer_elt_type
Rcpp::XPtr<rpjrt::PJRTElementType> impl_buffer_elt_type(Rcpp::XPtr<rpjrt::PJRTBuffer> buffer);
RcppExport SEXP _pjrt_impl_buffer_elt_type(SEXP bufferSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTBuffer> >::type buffer(bufferSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_buffer_elt_type(buffer));
    return rcpp_result_gen;
END_RCPP
}
// impl_buffer_device
Rcpp::XPtr<rpjrt::PJRTDevice> impl_buffer_device(Rcpp::XPtr<rpjrt::PJRTBuffer> buffer);
RcppExport SEXP _pjrt_impl_buffer_device(SEXP bufferSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTBuffer> >::type buffer(bufferSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_buffer_device(buffer));
    return rcpp_result_gen;
END_RCPP
}
// impl_buffer_memory
Rcpp::XPtr<rpjrt::PJRTMemory> impl_buffer_memory(Rcpp::XPtr<rpjrt::PJRTBuffer> buffer);
RcppExport SEXP _pjrt_impl_buffer_memory(SEXP bufferSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTBuffer> >::type buffer(bufferSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_buffer_memory(buffer));
    return rcpp_result_gen;
END_RCPP
}
// impl_memory_debug_string
std::string impl_memory_debug_string(Rcpp::XPtr<rpjrt::PJRTMemory> memory);
RcppExport SEXP _pjrt_impl_memory_debug_string(SEXP memorySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTMemory> >::type memory(memorySEXP);
    rcpp_result_gen = Rcpp::wrap(impl_memory_debug_string(memory));
    return rcpp_result_gen;
END_RCPP
}
// impl_memory_id
int impl_memory_id(Rcpp::XPtr<rpjrt::PJRTMemory> memory);
RcppExport SEXP _pjrt_impl_memory_id(SEXP memorySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTMemory> >::type memory(memorySEXP);
    rcpp_result_gen = Rcpp::wrap(impl_memory_id(memory));
    return rcpp_result_gen;
END_RCPP
}
// impl_memory_kind
std::string impl_memory_kind(Rcpp::XPtr<rpjrt::PJRTMemory> memory);
RcppExport SEXP _pjrt_impl_memory_kind(SEXP memorySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTMemory> >::type memory(memorySEXP);
    rcpp_result_gen = Rcpp::wrap(impl_memory_kind(memory));
    return rcpp_result_gen;
END_RCPP
}
// impl_memory_to_string
std::string impl_memory_to_string(Rcpp::XPtr<rpjrt::PJRTMemory> memory);
RcppExport SEXP _pjrt_impl_memory_to_string(SEXP memorySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTMemory> >::type memory(memorySEXP);
    rcpp_result_gen = Rcpp::wrap(impl_memory_to_string(memory));
    return rcpp_result_gen;
END_RCPP
}
// impl_dtype_as_string
std::string impl_dtype_as_string(Rcpp::XPtr<rpjrt::PJRTElementType> element_type);
RcppExport SEXP _pjrt_impl_dtype_as_string(SEXP element_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTElementType> >::type element_type(element_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_dtype_as_string(element_type));
    return rcpp_result_gen;
END_RCPP
}
// impl_buffer_dimensions
Rcpp::IntegerVector impl_buffer_dimensions(Rcpp::XPtr<rpjrt::PJRTBuffer> buffer);
RcppExport SEXP _pjrt_impl_buffer_dimensions(SEXP bufferSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTBuffer> >::type buffer(bufferSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_buffer_dimensions(buffer));
    return rcpp_result_gen;
END_RCPP
}
// impl_execution_options_create
Rcpp::XPtr<rpjrt::PJRTExecuteOptions> impl_execution_options_create(std::vector<int64_t> non_donatable_input_indices, int launch_id);
RcppExport SEXP _pjrt_impl_execution_options_create(SEXP non_donatable_input_indicesSEXP, SEXP launch_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int64_t> >::type non_donatable_input_indices(non_donatable_input_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type launch_id(launch_idSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_execution_options_create(non_donatable_input_indices, launch_id));
    return rcpp_result_gen;
END_RCPP
}
// impl_plugin_pjrt_api_version
Rcpp::IntegerVector impl_plugin_pjrt_api_version(Rcpp::XPtr<rpjrt::PJRTPlugin> plugin);
RcppExport SEXP _pjrt_impl_plugin_pjrt_api_version(SEXP pluginSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTPlugin> >::type plugin(pluginSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_plugin_pjrt_api_version(plugin));
    return rcpp_result_gen;
END_RCPP
}
// impl_plugin_attributes
Rcpp::List impl_plugin_attributes(Rcpp::XPtr<rpjrt::PJRTPlugin> plugin);
RcppExport SEXP _pjrt_impl_plugin_attributes(SEXP pluginSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTPlugin> >::type plugin(pluginSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_plugin_attributes(plugin));
    return rcpp_result_gen;
END_RCPP
}
// impl_device_to_string
std::string impl_device_to_string(Rcpp::XPtr<rpjrt::PJRTDevice> device);
RcppExport SEXP _pjrt_impl_device_to_string(SEXP deviceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTDevice> >::type device(deviceSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_device_to_string(device));
    return rcpp_result_gen;
END_RCPP
}
// impl_buffer_print
void impl_buffer_print(Rcpp::XPtr<rpjrt::PJRTBuffer> buffer, int max_rows, int max_width, int max_rows_slice);
RcppExport SEXP _pjrt_impl_buffer_print(SEXP bufferSEXP, SEXP max_rowsSEXP, SEXP max_widthSEXP, SEXP max_rows_sliceSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTBuffer> >::type buffer(bufferSEXP);
    Rcpp::traits::input_parameter< int >::type max_rows(max_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type max_width(max_widthSEXP);
    Rcpp::traits::input_parameter< int >::type max_rows_slice(max_rows_sliceSEXP);
    impl_buffer_print(buffer, max_rows, max_width, max_rows_slice);
    return R_NilValue;
END_RCPP
}
// impl_buffer_is_ready
bool impl_buffer_is_ready(Rcpp::XPtr<rpjrt::PJRTBuffer> buffer);
RcppExport SEXP _pjrt_impl_buffer_is_ready(SEXP bufferSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTBuffer> >::type buffer(bufferSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_buffer_is_ready(buffer));
    return rcpp_result_gen;
END_RCPP
}
// impl_buffer_await
void impl_buffer_await(Rcpp::XPtr<rpjrt::PJRTBuffer> buffer);
RcppExport SEXP _pjrt_impl_buffer_await(SEXP bufferSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTBuffer> >::type buffer(bufferSEXP);
    impl_buffer_await(buffer);
    return R_NilValue;
END_RCPP
}
// impl_host_data_is_ready
bool impl_host_data_is_ready(Rcpp::XPtr<rpjrt::PJRTHostData> data);
RcppExport SEXP _pjrt_impl_host_data_is_ready(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTHostData> >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_host_data_is_ready(data));
    return rcpp_result_gen;
END_RCPP
}
// impl_host_data_await
void impl_host_data_await(Rcpp::XPtr<rpjrt::PJRTHostData> data);
RcppExport SEXP _pjrt_impl_host_data_await(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTHostData> >::type data(dataSEXP);
    impl_host_data_await(data);
    return R_NilValue;
END_RCPP
}
// impl_process_pending_releases
void impl_process_pending_releases();
RcppExport SEXP _pjrt_impl_process_pending_releases() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    impl_process_pending_releases();
    return R_NilValue;
END_RCPP
}
// impl_pending_release_count
std::size_t impl_pending_release_count();
RcppExport SEXP _pjrt_impl_pending_release_count() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(impl_pending_release_count());
    return rcpp_result_gen;
END_RCPP
}
// impl_test_enqueue_release
void impl_test_enqueue_release(SEXP x);
RcppExport SEXP _pjrt_impl_test_enqueue_release(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    impl_test_enqueue_release(x);
    return R_NilValue;
END_RCPP
}
// impl_raw_to_array
SEXP impl_raw_to_array(Rcpp::XPtr<rpjrt::PJRTHostData> host_data, const std::string& dtype, Rcpp::IntegerVector dims, Rcpp::IntegerVector minor_to_major);
RcppExport SEXP _pjrt_impl_raw_to_array(SEXP host_dataSEXP, SEXP dtypeSEXP, SEXP dimsSEXP, SEXP minor_to_majorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTHostData> >::type host_data(host_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dtype(dtypeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type minor_to_major(minor_to_majorSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_raw_to_array(host_data, dtype, dims, minor_to_major));
    return rcpp_result_gen;
END_RCPP
}
// impl_buffer_to_host_async
Rcpp::List impl_buffer_to_host_async(Rcpp::XPtr<rpjrt::PJRTBuffer> buffer);
RcppExport SEXP _pjrt_impl_buffer_to_host_async(SEXP bufferSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTBuffer> >::type buffer(bufferSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_buffer_to_host_async(buffer));
    return rcpp_result_gen;
END_RCPP
}
// impl_loaded_executable_aliases
Rcpp::List impl_loaded_executable_aliases(Rcpp::XPtr<rpjrt::PJRTLoadedExecutable> executable);
RcppExport SEXP _pjrt_impl_loaded_executable_aliases(SEXP executableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTLoadedExecutable> >::type executable(executableSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_loaded_executable_aliases(executable));
    return rcpp_result_gen;
END_RCPP
}
// impl_loaded_executable_execute
Rcpp::List impl_loaded_executable_execute(Rcpp::XPtr<rpjrt::PJRTLoadedExecutable> executable, Rcpp::List input, Rcpp::XPtr<rpjrt::PJRTExecuteOptions> execution_options);
RcppExport SEXP _pjrt_impl_loaded_executable_execute(SEXP executableSEXP, SEXP inputSEXP, SEXP execution_optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTLoadedExecutable> >::type executable(executableSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type input(inputSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTExecuteOptions> >::type execution_options(execution_optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_loaded_executable_execute(executable, input, execution_options));
    return rcpp_result_gen;
END_RCPP
}
// impl_client_buffer_from_integer
Rcpp::XPtr<rpjrt::PJRTBuffer> impl_client_buffer_from_integer(Rcpp::XPtr<rpjrt::PJRTClient> client, Rcpp::XPtr<rpjrt::PJRTDevice> device, SEXP data, std::vector<int64_t> dims, std::string dtype);
RcppExport SEXP _pjrt_impl_client_buffer_from_integer(SEXP clientSEXP, SEXP deviceSEXP, SEXP dataSEXP, SEXP dimsSEXP, SEXP dtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTClient> >::type client(clientSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTDevice> >::type device(deviceSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::vector<int64_t> >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_client_buffer_from_integer(client, device, data, dims, dtype));
    return rcpp_result_gen;
END_RCPP
}
// impl_client_buffer_from_integer64
Rcpp::XPtr<rpjrt::PJRTBuffer> impl_client_buffer_from_integer64(Rcpp::XPtr<rpjrt::PJRTClient> client, Rcpp::XPtr<rpjrt::PJRTDevice> device, SEXP data, std::vector<int64_t> dims, std::string dtype);
RcppExport SEXP _pjrt_impl_client_buffer_from_integer64(SEXP clientSEXP, SEXP deviceSEXP, SEXP dataSEXP, SEXP dimsSEXP, SEXP dtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTClient> >::type client(clientSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTDevice> >::type device(deviceSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::vector<int64_t> >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_client_buffer_from_integer64(client, device, data, dims, dtype));
    return rcpp_result_gen;
END_RCPP
}
// impl_client_buffer_from_logical
Rcpp::XPtr<rpjrt::PJRTBuffer> impl_client_buffer_from_logical(Rcpp::XPtr<rpjrt::PJRTClient> client, Rcpp::XPtr<rpjrt::PJRTDevice> device, SEXP data, std::vector<int64_t> dims, std::string dtype);
RcppExport SEXP _pjrt_impl_client_buffer_from_logical(SEXP clientSEXP, SEXP deviceSEXP, SEXP dataSEXP, SEXP dimsSEXP, SEXP dtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTClient> >::type client(clientSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTDevice> >::type device(deviceSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::vector<int64_t> >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_client_buffer_from_logical(client, device, data, dims, dtype));
    return rcpp_result_gen;
END_RCPP
}
// impl_client_buffer_from_double
Rcpp::XPtr<rpjrt::PJRTBuffer> impl_client_buffer_from_double(Rcpp::XPtr<rpjrt::PJRTClient> client, Rcpp::XPtr<rpjrt::PJRTDevice> device, SEXP data, std::vector<int64_t> dims, std::string dtype);
RcppExport SEXP _pjrt_impl_client_buffer_from_double(SEXP clientSEXP, SEXP deviceSEXP, SEXP dataSEXP, SEXP dimsSEXP, SEXP dtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTClient> >::type client(clientSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<rpjrt::PJRTDevice> >::type device(deviceSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::vector<int64_t> >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_client_buffer_from_double(client, device, data, dims, dtype));
    return rcpp_result_gen;
END_RCPP
}
// get_geqrf_handler
SEXP get_geqrf_handler();
RcppExport SEXP _pjrt_get_geqrf_handler() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_geqrf_handler());
    return rcpp_result_gen;
END_RCPP
}
// get_orgqr_handler
SEXP get_orgqr_handler();
RcppExport SEXP _pjrt_get_orgqr_handler() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_orgqr_handler());
    return rcpp_result_gen;
END_RCPP
}
// get_geqrf_handler_cuda
SEXP get_geqrf_handler_cuda();
RcppExport SEXP _pjrt_get_geqrf_handler_cuda() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_geqrf_handler_cuda());
    return rcpp_result_gen;
END_RCPP
}
// get_orgqr_handler_cuda
SEXP get_orgqr_handler_cuda();
RcppExport SEXP _pjrt_get_orgqr_handler_cuda() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_orgqr_handler_cuda());
    return rcpp_result_gen;
END_RCPP
}
// get_svd_handler
SEXP get_svd_handler();
RcppExport SEXP _pjrt_get_svd_handler() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_svd_handler());
    return rcpp_result_gen;
END_RCPP
}
// get_svd_handler_cuda
SEXP get_svd_handler_cuda();
RcppExport SEXP _pjrt_get_svd_handler_cuda() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_svd_handler_cuda());
    return rcpp_result_gen;
END_RCPP
}
// impl_test_xptr_prot
SEXP impl_test_xptr_prot(SEXP x);
RcppExport SEXP _pjrt_impl_test_xptr_prot(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_test_xptr_prot(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pjrt_impl_dispatch_node_selftest", (DL_FUNC) &_pjrt_impl_dispatch_node_selftest, 1},
    {"_pjrt_impl_dispatch_key_hash", (DL_FUNC) &_pjrt_impl_dispatch_key_hash, 1},
    {"_pjrt_impl_dispatch_key_eq", (DL_FUNC) &_pjrt_impl_dispatch_key_eq, 2},
    {"_pjrt_impl_dispatch_static_key_eq", (DL_FUNC) &_pjrt_impl_dispatch_static_key_eq, 2},
    {"_pjrt_impl_dispatch_lru_selftest", (DL_FUNC) &_pjrt_impl_dispatch_lru_selftest, 0},
    {"_pjrt_impl_dispatch_sentinel", (DL_FUNC) &_pjrt_impl_dispatch_sentinel, 0},
    {"_pjrt_impl_dispatch_create", (DL_FUNC) &_pjrt_impl_dispatch_create, 2},
    {"_pjrt_impl_dispatch_size", (DL_FUNC) &_pjrt_impl_dispatch_size, 1},
    {"_pjrt_impl_dispatch_run", (DL_FUNC) &_pjrt_impl_dispatch_run, 2},
    {"_pjrt_get_eigh_handler", (DL_FUNC) &_pjrt_get_eigh_handler, 0},
    {"_pjrt_get_eigh_handler_cuda", (DL_FUNC) &_pjrt_get_eigh_handler_cuda, 0},
    {"_pjrt_impl_register_custom_call", (DL_FUNC) &_pjrt_impl_register_custom_call, 4},
    {"_pjrt_get_print_handler", (DL_FUNC) &_pjrt_get_print_handler, 0},
    {"_pjrt_get_print_handler_cuda", (DL_FUNC) &_pjrt_get_print_handler_cuda, 0},
    {"_pjrt_test_get_extension", (DL_FUNC) &_pjrt_test_get_extension, 2},
    {"_pjrt_format_raw_buffer_cpp", (DL_FUNC) &_pjrt_format_raw_buffer_cpp, 3},
    {"_pjrt_impl_gc_call_count", (DL_FUNC) &_pjrt_impl_gc_call_count, 0},
    {"_pjrt_impl_call_r_gc", (DL_FUNC) &_pjrt_impl_call_r_gc, 0},
    {"_pjrt_get_lu_handler", (DL_FUNC) &_pjrt_get_lu_handler, 0},
    {"_pjrt_get_lu_handler_cuda", (DL_FUNC) &_pjrt_get_lu_handler_cuda, 0},
    {"_pjrt_impl_plugin_load", (DL_FUNC) &_pjrt_impl_plugin_load, 1},
    {"_pjrt_impl_plugin_client_create", (DL_FUNC) &_pjrt_impl_plugin_client_create, 2},
    {"_pjrt_impl_program_load", (DL_FUNC) &_pjrt_impl_program_load, 2},
    {"_pjrt_impl_program_repr", (DL_FUNC) &_pjrt_impl_program_repr, 2},
    {"_pjrt_impl_build_options_create", (DL_FUNC) &_pjrt_impl_build_options_create, 3},
    {"_pjrt_impl_compile_options_create", (DL_FUNC) &_pjrt_impl_compile_options_create, 1},
    {"_pjrt_impl_client_program_compile", (DL_FUNC) &_pjrt_impl_client_program_compile, 4},
    {"_pjrt_impl_loaded_executable_device", (DL_FUNC) &_pjrt_impl_loaded_executable_device, 1},
    {"_pjrt_impl_client_buffer_from_raw", (DL_FUNC) &_pjrt_impl_client_buffer_from_raw, 6},
    {"_pjrt_impl_client_buffer_empty", (DL_FUNC) &_pjrt_impl_client_buffer_empty, 4},
    {"_pjrt_impl_buffer_to_raw", (DL_FUNC) &_pjrt_impl_buffer_to_raw, 3},
    {"_pjrt_impl_buffer_copy_to_device", (DL_FUNC) &_pjrt_impl_buffer_copy_to_device, 4},
    {"_pjrt_impl_client_platform", (DL_FUNC) &_pjrt_impl_client_platform, 1},
    {"_pjrt_impl_client_devices", (DL_FUNC) &_pjrt_impl_client_devices, 1},
    {"_pjrt_impl_buffer_elt_type", (DL_FUNC) &_pjrt_impl_buffer_elt_type, 1},
    {"_pjrt_impl_buffer_device", (DL_FUNC) &_pjrt_impl_buffer_device, 1},
    {"_pjrt_impl_buffer_memory", (DL_FUNC) &_pjrt_impl_buffer_memory, 1},
    {"_pjrt_impl_memory_debug_string", (DL_FUNC) &_pjrt_impl_memory_debug_string, 1},
    {"_pjrt_impl_memory_id", (DL_FUNC) &_pjrt_impl_memory_id, 1},
    {"_pjrt_impl_memory_kind", (DL_FUNC) &_pjrt_impl_memory_kind, 1},
    {"_pjrt_impl_memory_to_string", (DL_FUNC) &_pjrt_impl_memory_to_string, 1},
    {"_pjrt_impl_dtype_as_string", (DL_FUNC) &_pjrt_impl_dtype_as_string, 1},
    {"_pjrt_impl_buffer_dimensions", (DL_FUNC) &_pjrt_impl_buffer_dimensions, 1},
    {"_pjrt_impl_execution_options_create", (DL_FUNC) &_pjrt_impl_execution_options_create, 2},
    {"_pjrt_impl_plugin_pjrt_api_version", (DL_FUNC) &_pjrt_impl_plugin_pjrt_api_version, 1},
    {"_pjrt_impl_plugin_attributes", (DL_FUNC) &_pjrt_impl_plugin_attributes, 1},
    {"_pjrt_impl_device_to_string", (DL_FUNC) &_pjrt_impl_device_to_string, 1},
    {"_pjrt_impl_buffer_print", (DL_FUNC) &_pjrt_impl_buffer_print, 4},
    {"_pjrt_impl_buffer_is_ready", (DL_FUNC) &_pjrt_impl_buffer_is_ready, 1},
    {"_pjrt_impl_buffer_await", (DL_FUNC) &_pjrt_impl_buffer_await, 1},
    {"_pjrt_impl_host_data_is_ready", (DL_FUNC) &_pjrt_impl_host_data_is_ready, 1},
    {"_pjrt_impl_host_data_await", (DL_FUNC) &_pjrt_impl_host_data_await, 1},
    {"_pjrt_impl_process_pending_releases", (DL_FUNC) &_pjrt_impl_process_pending_releases, 0},
    {"_pjrt_impl_pending_release_count", (DL_FUNC) &_pjrt_impl_pending_release_count, 0},
    {"_pjrt_impl_test_enqueue_release", (DL_FUNC) &_pjrt_impl_test_enqueue_release, 1},
    {"_pjrt_impl_raw_to_array", (DL_FUNC) &_pjrt_impl_raw_to_array, 4},
    {"_pjrt_impl_buffer_to_host_async", (DL_FUNC) &_pjrt_impl_buffer_to_host_async, 1},
    {"_pjrt_impl_loaded_executable_aliases", (DL_FUNC) &_pjrt_impl_loaded_executable_aliases, 1},
    {"_pjrt_impl_loaded_executable_execute", (DL_FUNC) &_pjrt_impl_loaded_executable_execute, 3},
    {"_pjrt_impl_client_buffer_from_integer", (DL_FUNC) &_pjrt_impl_client_buffer_from_integer, 5},
    {"_pjrt_impl_client_buffer_from_integer64", (DL_FUNC) &_pjrt_impl_client_buffer_from_integer64, 5},
    {"_pjrt_impl_client_buffer_from_logical", (DL_FUNC) &_pjrt_impl_client_buffer_from_logical, 5},
    {"_pjrt_impl_client_buffer_from_double", (DL_FUNC) &_pjrt_impl_client_buffer_from_double, 5},
    {"_pjrt_get_geqrf_handler", (DL_FUNC) &_pjrt_get_geqrf_handler, 0},
    {"_pjrt_get_orgqr_handler", (DL_FUNC) &_pjrt_get_orgqr_handler, 0},
    {"_pjrt_get_geqrf_handler_cuda", (DL_FUNC) &_pjrt_get_geqrf_handler_cuda, 0},
    {"_pjrt_get_orgqr_handler_cuda", (DL_FUNC) &_pjrt_get_orgqr_handler_cuda, 0},
    {"_pjrt_get_svd_handler", (DL_FUNC) &_pjrt_get_svd_handler, 0},
    {"_pjrt_get_svd_handler_cuda", (DL_FUNC) &_pjrt_get_svd_handler_cuda, 0},
    {"_pjrt_impl_test_xptr_prot", (DL_FUNC) &_pjrt_impl_test_xptr_prot, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_pjrt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
