# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_tests_enabled <- function() {
    .Call(`_pjrt_cpp_tests_enabled`)
}

impl_dispatch_create <- function(capacity, miss_fn, static_names, engine, backend, move_inputs, default_device_fn, extractor_fn) {
    .Call(`_pjrt_impl_dispatch_create`, capacity, miss_fn, static_names, engine, backend, move_inputs, default_device_fn, extractor_fn)
}

impl_dispatcher_size <- function(dispatcher) {
    .Call(`_pjrt_impl_dispatcher_size`, dispatcher)
}

impl_dispatch_run <- function(dispatcher, args) {
    .Call(`_pjrt_impl_dispatch_run`, dispatcher, args)
}

get_eigh_handler <- function() {
    .Call(`_pjrt_get_eigh_handler`)
}

get_eigh_handler_cuda <- function() {
    .Call(`_pjrt_get_eigh_handler_cuda`)
}

impl_register_custom_call <- function(plugin, target_name, handler_ptr, platform_name) {
    invisible(.Call(`_pjrt_impl_register_custom_call`, plugin, target_name, handler_ptr, platform_name))
}

get_print_handler <- function() {
    .Call(`_pjrt_get_print_handler`)
}

get_print_handler_cuda <- function() {
    .Call(`_pjrt_get_print_handler_cuda`)
}

test_get_extension <- function(plugin, platform_name) {
    .Call(`_pjrt_test_get_extension`, plugin, platform_name)
}

format_raw_buffer_cpp <- function(data, dtype, shape) {
    .Call(`_pjrt_format_raw_buffer_cpp`, data, dtype, shape)
}

impl_gc_call_count <- function() {
    .Call(`_pjrt_impl_gc_call_count`)
}

impl_call_r_gc <- function() {
    invisible(.Call(`_pjrt_impl_call_r_gc`))
}

get_lu_handler <- function() {
    .Call(`_pjrt_get_lu_handler`)
}

get_lu_handler_cuda <- function() {
    .Call(`_pjrt_get_lu_handler_cuda`)
}

impl_plugin_load <- function(path) {
    .Call(`_pjrt_impl_plugin_load`, path)
}

impl_plugin_client_create <- function(plugin, options = NULL) {
    .Call(`_pjrt_impl_plugin_client_create`, plugin, options)
}

impl_program_load <- function(fname, format) {
    .Call(`_pjrt_impl_program_load`, fname, format)
}

impl_program_repr <- function(program, n = 10L) {
    .Call(`_pjrt_impl_program_repr`, program, n)
}

impl_build_options_create <- function(num_replicas = 1L, num_partitions = 1L, device_ordinal = -1L) {
    .Call(`_pjrt_impl_build_options_create`, num_replicas, num_partitions, device_ordinal)
}

impl_compile_options_create <- function(build_options) {
    .Call(`_pjrt_impl_compile_options_create`, build_options)
}

impl_client_program_compile <- function(client, device, program, compile_options) {
    .Call(`_pjrt_impl_client_program_compile`, client, device, program, compile_options)
}

impl_loaded_executable_device <- function(executable) {
    .Call(`_pjrt_impl_loaded_executable_device`, executable)
}

impl_client_buffer_from_raw <- function(client, device, data, dims, dtype, row_major = FALSE) {
    .Call(`_pjrt_impl_client_buffer_from_raw`, client, device, data, dims, dtype, row_major)
}

impl_client_buffer_empty <- function(client, device, dims, dtype) {
    .Call(`_pjrt_impl_client_buffer_empty`, client, device, dims, dtype)
}

impl_buffer_to_raw <- function(client, buffer, row_major = FALSE) {
    .Call(`_pjrt_impl_buffer_to_raw`, client, buffer, row_major)
}

impl_buffer_copy_to_device <- function(buffer, device, dst_client, cross_client) {
    .Call(`_pjrt_impl_buffer_copy_to_device`, buffer, device, dst_client, cross_client)
}

impl_client_platform <- function(client) {
    .Call(`_pjrt_impl_client_platform`, client)
}

impl_client_devices <- function(client) {
    .Call(`_pjrt_impl_client_devices`, client)
}

impl_buffer_elt_type <- function(buffer) {
    .Call(`_pjrt_impl_buffer_elt_type`, buffer)
}

impl_buffer_device <- function(buffer) {
    .Call(`_pjrt_impl_buffer_device`, buffer)
}

impl_buffer_memory <- function(buffer) {
    .Call(`_pjrt_impl_buffer_memory`, buffer)
}

impl_memory_debug_string <- function(memory) {
    .Call(`_pjrt_impl_memory_debug_string`, memory)
}

impl_memory_id <- function(memory) {
    .Call(`_pjrt_impl_memory_id`, memory)
}

impl_memory_kind <- function(memory) {
    .Call(`_pjrt_impl_memory_kind`, memory)
}

impl_memory_to_string <- function(memory) {
    .Call(`_pjrt_impl_memory_to_string`, memory)
}

impl_dtype_as_string <- function(element_type) {
    .Call(`_pjrt_impl_dtype_as_string`, element_type)
}

impl_buffer_dimensions <- function(buffer) {
    .Call(`_pjrt_impl_buffer_dimensions`, buffer)
}

impl_execution_options_create <- function(non_donatable_input_indices, launch_id) {
    .Call(`_pjrt_impl_execution_options_create`, non_donatable_input_indices, launch_id)
}

impl_plugin_pjrt_api_version <- function(plugin) {
    .Call(`_pjrt_impl_plugin_pjrt_api_version`, plugin)
}

impl_plugin_attributes <- function(plugin) {
    .Call(`_pjrt_impl_plugin_attributes`, plugin)
}

impl_device_to_string <- function(device) {
    .Call(`_pjrt_impl_device_to_string`, device)
}

impl_buffer_print <- function(buffer, max_rows, max_width, max_rows_slice) {
    invisible(.Call(`_pjrt_impl_buffer_print`, buffer, max_rows, max_width, max_rows_slice))
}

impl_buffer_is_ready <- function(buffer) {
    .Call(`_pjrt_impl_buffer_is_ready`, buffer)
}

impl_buffer_await <- function(buffer) {
    invisible(.Call(`_pjrt_impl_buffer_await`, buffer))
}

impl_host_data_is_ready <- function(data) {
    .Call(`_pjrt_impl_host_data_is_ready`, data)
}

impl_host_data_await <- function(data) {
    invisible(.Call(`_pjrt_impl_host_data_await`, data))
}

impl_process_pending_releases <- function() {
    invisible(.Call(`_pjrt_impl_process_pending_releases`))
}

impl_pending_release_count <- function() {
    .Call(`_pjrt_impl_pending_release_count`)
}

impl_test_enqueue_release <- function(x) {
    invisible(.Call(`_pjrt_impl_test_enqueue_release`, x))
}

impl_raw_to_array <- function(host_data, dtype, dims, minor_to_major) {
    .Call(`_pjrt_impl_raw_to_array`, host_data, dtype, dims, minor_to_major)
}

impl_buffer_to_host_async <- function(buffer) {
    .Call(`_pjrt_impl_buffer_to_host_async`, buffer)
}

impl_loaded_executable_aliases <- function(executable) {
    .Call(`_pjrt_impl_loaded_executable_aliases`, executable)
}

impl_loaded_executable_execute <- function(executable, input, execution_options) {
    .Call(`_pjrt_impl_loaded_executable_execute`, executable, input, execution_options)
}

impl_client_buffer_from_integer <- function(client, device, data, dims, dtype) {
    .Call(`_pjrt_impl_client_buffer_from_integer`, client, device, data, dims, dtype)
}

impl_client_buffer_from_integer64 <- function(client, device, data, dims, dtype) {
    .Call(`_pjrt_impl_client_buffer_from_integer64`, client, device, data, dims, dtype)
}

impl_client_buffer_from_logical <- function(client, device, data, dims, dtype) {
    .Call(`_pjrt_impl_client_buffer_from_logical`, client, device, data, dims, dtype)
}

impl_client_buffer_from_double <- function(client, device, data, dims, dtype) {
    .Call(`_pjrt_impl_client_buffer_from_double`, client, device, data, dims, dtype)
}

get_geqrf_handler <- function() {
    .Call(`_pjrt_get_geqrf_handler`)
}

get_orgqr_handler <- function() {
    .Call(`_pjrt_get_orgqr_handler`)
}

get_geqrf_handler_cuda <- function() {
    .Call(`_pjrt_get_geqrf_handler_cuda`)
}

get_orgqr_handler_cuda <- function() {
    .Call(`_pjrt_get_orgqr_handler_cuda`)
}

get_svd_handler <- function() {
    .Call(`_pjrt_get_svd_handler`)
}

get_svd_handler_cuda <- function() {
    .Call(`_pjrt_get_svd_handler_cuda`)
}

impl_tree_build <- function(x) {
    .Call(`_pjrt_impl_tree_build`, x)
}

impl_tree_build_flatten <- function(x) {
    .Call(`_pjrt_impl_tree_build_flatten`, x)
}

impl_tree_unflatten <- function(tree, x) {
    .Call(`_pjrt_impl_tree_unflatten`, tree, x)
}

impl_tree_size <- function(tree) {
    .Call(`_pjrt_impl_tree_size`, tree)
}

impl_tree_equal <- function(a, b) {
    .Call(`_pjrt_impl_tree_equal`, a, b)
}

impl_tree_hash <- function(tree) {
    .Call(`_pjrt_impl_tree_hash`, tree)
}

impl_tree_kind <- function(tree) {
    .Call(`_pjrt_impl_tree_kind`, tree)
}

impl_tree_child_names <- function(tree) {
    .Call(`_pjrt_impl_tree_child_names`, tree)
}

impl_tree_child_kinds <- function(tree) {
    .Call(`_pjrt_impl_tree_child_kinds`, tree)
}

impl_tree_child_sizes <- function(tree) {
    .Call(`_pjrt_impl_tree_child_sizes`, tree)
}

impl_tree_path <- function(tree, i) {
    .Call(`_pjrt_impl_tree_path`, tree, i)
}

impl_tree_filter_by_names <- function(tree, names) {
    .Call(`_pjrt_impl_tree_filter_by_names`, tree, names)
}

impl_tree_concat <- function(children, names) {
    .Call(`_pjrt_impl_tree_concat`, children, names)
}

impl_tree_mask_from_names <- function(tree, names) {
    .Call(`_pjrt_impl_tree_mask_from_names`, tree, names)
}

impl_tree_repr <- function(tree) {
    .Call(`_pjrt_impl_tree_repr`, tree)
}

impl_tree_diff <- function(a, b) {
    .Call(`_pjrt_impl_tree_diff`, a, b)
}

impl_test_xptr_prot <- function(x) {
    .Call(`_pjrt_impl_test_xptr_prot`, x)
}

