# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

impl_plugin_load <- function(path) {
    .Call(`_pjrt_impl_plugin_load`, path)
}

impl_plugin_client_create <- function(plugin) {
    .Call(`_pjrt_impl_plugin_client_create`, plugin)
}

impl_program_load <- function(fname, format) {
    .Call(`_pjrt_impl_program_load`, fname, format)
}

impl_program_repr <- function(program, n = 10L) {
    .Call(`_pjrt_impl_program_repr`, program, n)
}

impl_build_options_create <- function(num_replicas = 1L, num_partitions = 1L, device_ordinal = -1L) {
    .Call(`_pjrt_impl_build_options_create`, num_replicas, num_partitions, device_ordinal)
}

impl_compile_options_create <- function(build_options) {
    .Call(`_pjrt_impl_compile_options_create`, build_options)
}

impl_client_program_compile <- function(client, program, compile_options) {
    .Call(`_pjrt_impl_client_program_compile`, client, program, compile_options)
}

impl_client_scalar_buffer_from_host <- function(client, data) {
    .Call(`_pjrt_impl_client_scalar_buffer_from_host`, client, data)
}

impl_client_buffer_from_host <- function(client, data) {
    .Call(`_pjrt_impl_client_buffer_from_host`, client, data)
}

impl_client_buffer_to_host <- function(client, buffer) {
    .Call(`_pjrt_impl_client_buffer_to_host`, client, buffer)
}

impl_loaded_executable_execute <- function(executable, input) {
    .Call(`_pjrt_impl_loaded_executable_execute`, executable, input)
}

