# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_get_extension <- function(plugin) {
    .Call(`_pjrt_test_get_extension`, plugin)
}

format_raw_buffer_cpp <- function(data, dtype, shape) {
    .Call(`_pjrt_format_raw_buffer_cpp`, data, dtype, shape)
}

impl_plugin_load <- function(path) {
    .Call(`_pjrt_impl_plugin_load`, path)
}

impl_plugin_client_create <- function(plugin, options = NULL) {
    .Call(`_pjrt_impl_plugin_client_create`, plugin, options)
}

impl_program_load <- function(fname, format) {
    .Call(`_pjrt_impl_program_load`, fname, format)
}

impl_program_repr <- function(program, n = 10L) {
    .Call(`_pjrt_impl_program_repr`, program, n)
}

impl_build_options_create <- function(num_replicas = 1L, num_partitions = 1L, device_ordinal = -1L) {
    .Call(`_pjrt_impl_build_options_create`, num_replicas, num_partitions, device_ordinal)
}

impl_compile_options_create <- function(build_options) {
    .Call(`_pjrt_impl_compile_options_create`, build_options)
}

impl_client_program_compile <- function(client, program, compile_options) {
    .Call(`_pjrt_impl_client_program_compile`, client, program, compile_options)
}

impl_client_buffer_from_integer <- function(client, device, data, dims, dtype) {
    .Call(`_pjrt_impl_client_buffer_from_integer`, client, device, data, dims, dtype)
}

impl_client_buffer_from_logical <- function(client, device, data, dims, dtype) {
    .Call(`_pjrt_impl_client_buffer_from_logical`, client, device, data, dims, dtype)
}

impl_client_buffer_from_raw <- function(client, device, data, dims, dtype, row_major = FALSE) {
    .Call(`_pjrt_impl_client_buffer_from_raw`, client, device, data, dims, dtype, row_major)
}

impl_client_buffer_from_double <- function(client, device, data, dims, dtype) {
    .Call(`_pjrt_impl_client_buffer_from_double`, client, device, data, dims, dtype)
}

impl_client_buffer_to_array <- function(client, buffer) {
    .Call(`_pjrt_impl_client_buffer_to_array`, client, buffer)
}

impl_client_buffer_to_raw <- function(client, buffer, row_major = FALSE) {
    .Call(`_pjrt_impl_client_buffer_to_raw`, client, buffer, row_major)
}

impl_client_platform <- function(client) {
    .Call(`_pjrt_impl_client_platform`, client)
}

impl_client_devices <- function(client) {
    .Call(`_pjrt_impl_client_devices`, client)
}

impl_loaded_executable_execute <- function(executable, input, execution_options) {
    .Call(`_pjrt_impl_loaded_executable_execute`, executable, input, execution_options)
}

impl_buffer_elt_type <- function(buffer) {
    .Call(`_pjrt_impl_buffer_elt_type`, buffer)
}

impl_buffer_device <- function(buffer) {
    .Call(`_pjrt_impl_buffer_device`, buffer)
}

impl_buffer_memory <- function(buffer) {
    .Call(`_pjrt_impl_buffer_memory`, buffer)
}

impl_memory_debug_string <- function(memory) {
    .Call(`_pjrt_impl_memory_debug_string`, memory)
}

impl_memory_id <- function(memory) {
    .Call(`_pjrt_impl_memory_id`, memory)
}

impl_memory_kind <- function(memory) {
    .Call(`_pjrt_impl_memory_kind`, memory)
}

impl_memory_to_string <- function(memory) {
    .Call(`_pjrt_impl_memory_to_string`, memory)
}

impl_dtype_as_string <- function(element_type) {
    .Call(`_pjrt_impl_dtype_as_string`, element_type)
}

impl_buffer_dimensions <- function(buffer) {
    .Call(`_pjrt_impl_buffer_dimensions`, buffer)
}

impl_execution_options_create <- function(non_donatable_input_indices, launch_id) {
    .Call(`_pjrt_impl_execution_options_create`, non_donatable_input_indices, launch_id)
}

impl_plugin_pjrt_api_version <- function(plugin) {
    .Call(`_pjrt_impl_plugin_pjrt_api_version`, plugin)
}

impl_plugin_attributes <- function(plugin) {
    .Call(`_pjrt_impl_plugin_attributes`, plugin)
}

impl_device_to_string <- function(device) {
    .Call(`_pjrt_impl_device_to_string`, device)
}

impl_device_platform <- function(device) {
    .Call(`_pjrt_impl_device_platform`, device)
}

impl_buffer_print <- function(buffer, max_rows, max_width, max_rows_slice) {
    invisible(.Call(`_pjrt_impl_buffer_print`, buffer, max_rows, max_width, max_rows_slice))
}

