# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: format-code

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format R code
        uses: rstudio/shiny-workflows/format-r-code@v1

      - name: Format C++ code
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '18'
          fallback-style: none

      - name: Run clang-format 20 style check
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: "20"
