on:
  push:
    branches: [main, master]
  pull_request:

name: Lint C++ Code

jobs:
  cpp-linter:
    uses: r-xla/actions/.github/workflows/cpp-linter.yaml@main
    with:
      extra-packages: "cuda12.8=?ignore"
      extra-repositories: "https://r-xla.r-universe.dev, https://cudatoolkit-repo.dfalbel.workers.dev"
