on:
  push:
    branches: [main, master]
  pull_request:
name: Lint C++ Code

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgload

      - name: Create compile_commands.json
        run: |
          Rscript -e "pkgload::load_all()"

      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: false
          thread-comments: false
          database: ${{ github.workspace }}/

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        run: exit 1
