on:
  push:
    branches: [main, master]
  pull_request:
name: Lint C++ Code

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2

      - name: Create compile_commands.json
        run: |
          install.packages("pkgload"); pkgload::use_compilation_db()

      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: false
          thread-comments: false

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        run: exit 1
