# pkgdown workflow of the mlr3 ecosystem v0.1.0
# https://github.com/mlr-org/actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

name: pkgdown

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      PJRT_DEVICE: 'cpu'

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install protobuf on macOS
        if: runner.os == 'macOS'
        run: |
          brew install protobuf@21
          brew link protobuf@21 --force --overwrite

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown
          needs: website

      - name: Install package
        run: R CMD INSTALL .

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          clean: false
          branch: gh-pages
          folder: docs
