on:
  push:
    branches: [main, master]
  pull_request:

name: test-coverage.yaml

permissions:
  id-token: write

jobs:
  test-coverage:
    uses: r-xla/actions/.github/workflows/test-coverage.yaml@main
    with:
      extra-packages: "cuda12.8=?ignore"
      extra-repositories: "https://r-xla.r-universe.dev, https://mlverse.r-universe.dev"
